#include "simulation/terrain.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <stdexcept>

namespace rts {
void Terrain::load_from_binary(const std::string& path) {
    std::ifstream input(path, std::ios::binary);
    if (!input) throw std::runtime_error("Heightmap file unavailable: " + path);
    
    heights_.resize(GRID_SIZE * GRID_SIZE);
    input.read(reinterpret_cast<char*>(heights_.data()), heights_.size() * sizeof(float));
    
    if (!input) throw std::runtime_error("Heightmap file read failed");
}

void Terrain::set_world_bounds(float width, float height) {
    if (width > 0.0f && height > 0.0f && std::isfinite(width) && std::isfinite(height)) {
        world_width_ = width;
        world_height_ = height;
    }
}

float Terrain::height_at(float x, float y) const {
    if (x < -world_width_ * 0.5f || x > world_width_ * 0.5f ||
        y < -world_height_ * 0.5f || y > world_height_ * 0.5f) {
        return 0.0f;
    }
    if (heights_.empty()) {
        return 0.0f;
    }

    // Match the vertices generated by Godot: the 320 samples include both
    // world edges. Interpolate the same triangle split used by
    // HeightMap.generate_terrain_mesh() so units do not jump between 125 m
    // sample plateaus while the visible terrain slopes smoothly beneath them.
    const float grid_x = std::clamp(
        (x / world_width_ + 0.5f) * static_cast<float>(GRID_SIZE - 1),
        0.0f, static_cast<float>(GRID_SIZE - 1));
    const float grid_y = std::clamp(
        (y / world_height_ + 0.5f) * static_cast<float>(GRID_SIZE - 1),
        0.0f, static_cast<float>(GRID_SIZE - 1));
    const int x0 = std::min(static_cast<int>(std::floor(grid_x)), GRID_SIZE - 2);
    const int y0 = std::min(static_cast<int>(std::floor(grid_y)), GRID_SIZE - 2);
    const float tx = grid_x - static_cast<float>(x0);
    const float ty = grid_y - static_cast<float>(y0);
    const float h00 = heights_[y0 * GRID_SIZE + x0];
    const float h10 = heights_[y0 * GRID_SIZE + x0 + 1];
    const float h01 = heights_[(y0 + 1) * GRID_SIZE + x0];
    const float h11 = heights_[(y0 + 1) * GRID_SIZE + x0 + 1];
    if (tx + ty <= 1.0f) {
        return h00 + tx * (h10 - h00) + ty * (h01 - h00);
    }
    return h11 + (1.0f - ty) * (h10 - h11) + (1.0f - tx) * (h01 - h11);
}
}
